//videos data
export const videoData = [
    {
        video: require('../../storage/video/video1.mp4'),
        postProfile:require('../../storage/images/img1.jpg'),
        title: 'Ram_Charam',
        description:'Feel the buity of nature',
        likes:'245k',
        isLike:false,
    },
    {
        video: require('../../storage/video/video2.mp4'),
        postProfile:require('../../storage/images/img1.jpg'),
        title: 'Nguyen',
        description:'Feel the buity of nature',
        likes:'299k',
        isLike:false,
    },
    {
        video: require('../../storage/video/video3.mp4'),
        postProfile:require('../../storage/images/img1.jpg'),
        title: 'Hoang',
        description:'Feel the buity of nature',
        likes:'45k',
        isLike:false,
    },
    {
        video: require('../../storage/video/video4.mp4'),
        postProfile:require('../../storage/images/img1.jpg'),
        title: 'Hung',
        description:'Feel the buity of nature',
        likes:'255k',
        isLike:false,
    },
];


/// Friends profile data
export const FriendsProfileData = [
    {
        name: 'John_Cena',
        accountName: 'John Cena',
        profileImage: require('../../storage/images/img1.jpg'),
        posts: 56,
        followers: 6542,
        following: 443,
        follow: false,
    },
    {
        name: 'David_nguyen',
        accountName: 'Đavid',
        profileImage: require('../../storage/images/img2.jpg'),
        posts: 36,
        followers: 6532,
        following: 999,
        follow: false,
    },
    {
        name: 'Mask_Valorant',
        accountName: 'Jr Mask',
        profileImage: require('../../storage/images/img3.jpg'),
        posts: 53,
        followers: 658,
        following: 773,
        follow: false,
    },
    {
        name: 'Jelly',
        accountName: 'John Must',
        profileImage: require('../../storage/images/img4.jpg'),
        posts: 58,
        followers: 642,
        following: 49,
        follow: false,
    },
    {
        name: 'John_Cena',
        accountName: 'John Cena',
        profileImage: require('../../storage/images/img1.jpg'),
        posts: 56,
        followers: 6542,
        following: 443,
        follow: false,
    },
    {
        name: 'John_Cena',
        accountName: 'John Cena',
        profileImage: require('../../storage/images/img1.jpg'),
        posts: 56,
        followers: 6542,
        following: 443,
        follow: false,
    },
    {
        name: 'John_Cena',
        accountName: 'John Cena',
        profileImage: require('../../storage/images/img1.jpg'),
        posts: 56,
        followers: 6542,
        following: 443,
        follow: false,
    },
    {
        name: 'John_Cena',
        accountName: 'John Cena',
        profileImage: require('../../storage/images/img1.jpg'),
        posts: 56,
        followers: 6542,
        following: 443,
        follow: false,
    },
    {
        name: 'John_Cena',
        accountName: 'John Cena',
        profileImage: require('../../storage/images/img1.jpg'),
        posts: 56,
        followers: 6542,
        following: 443,
        follow: false,
    },
    {
        name: 'John_Cena',
        accountName: 'John Cena',
        profileImage: require('../../storage/images/img1.jpg'),
        posts: 56,
        followers: 6542,
        following: 443,
        follow: false,
    },
    {
        name: 'John_Cena',
        accountName: 'John Cena',
        profileImage: require('../../storage/images/img1.jpg'),
        posts: 56,
        followers: 6542,
        following: 443,
        follow: false,
    },
    {
        name: 'John_Cena',
        accountName: 'John Cena',
        profileImage: require('../../storage/images/img1.jpg'),
        posts: 56,
        followers: 6542,
        following: 443,
        follow: false,
    },
]